Member insert#2
Sarada1101/student_dontneed_shop_dev pull request #45
Opened 2020-07-03 03:15 UTC by xenom0514

## issue 

close #2 

## やったこと 
+ サーブレットとjspを作った

## 変更によって期待される結果 
+ 会員情報登録できる

## 動作確認 

+ 

## 補足

ちゃんと動くかわからない
## その他

2020-07-03 04:40 UTC, NekoSarada1101 requested changes
javaの変数名の決めかたはコーディング規約に書いてあります。きちんと確認しておいてください。

servletのアノテーションも設計書に書いてあります。確認してください

あと全体的に無駄な空行が多くてとても見づらいです。ちゃんとフォーマッターを使って無駄な部分を削除してください。MacのEclipseならShift + Command + fでできます。

日誌管理システムのコードが残ってないなら[ここ](https://github.com/Sarada1101/DiaryManagementSysteml)からソースコードをクローンとかダウンロードとかして使ってください。

レビューの抜け漏れとかあるかもだけど指摘箇所はだいたい似た感じ（多分）なので自分で確認してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_check.jsp
> +<title>Insert title here</title>
会員情報登録確認に変更してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_check.jsp
> +<h2>入力フォーム</h2>
削除してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_check.jsp
> +     <input type="submit" value="確認">
「確認」を「登録」に変更してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_check.jsp
> +      <a href="/student_dontneed_shop_dev/WebContent/WEB-INF/jsp/member/member_login.jsp">戻る</a><br>
aタグからformに変更してください
servlet経由でログイン画面に戻るようにしてください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_complete.jsp
> +<a href="/student_dontneed_shop_dev/WebContent/WEB-INF/jsp/member/member_top.jsp">トップへ</a><br>
aタグからformに変更してください
servlet経由でログイン画面に戻るようにしてください
「トップへ」を「トップへ戻る」に変更してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_input.jsp
> +    <% String errorMessage = (String)session.getAttribute("errorMessage"); %>
<%%>のなかに次の処理を追加してください
+ セッションからmemberBeansを受け取る
+ memberBeansがnullならmemberBeansのすべての値に""をセットする

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_input.jsp
> +	if (memberBeans = nall ){
ifからelseまでの部分を削除してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_input.jsp
> +            <td><input type="text" value= <%=memberBeans.getMemberMail() %> name = "member_mail" ></td>
すべてのname属性の値をキャメルケース（例：memberMail）に変更してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_input.jsp
> +     <input type="submit" value="確認">
「確認」を「登録」に変更してください

2020-07-03 04:40 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_input.jsp
> +      <a href="/student_dontneed_shop_dev/WebContent/WEB-INF/jsp/member/member_login.jsp">戻る</a><br>
aタグからformに変更してください
servlet経由でログイン画面に戻るようにしてください

2020-07-03 04:40 UTC, Sarada1101 commented on src/shop/model/dao/UserDao.java
> +
↓を参考に書き直してください
```java
public AdminBeans fetchAdminLogin(String adminMail, String password) {
        PreparedStatement stmt = null;
        ResultSet rs = null;
        //戻り値を初期化
        AdminBeans adminBeans = null;
        try {
            //DBのオープン
            this.connect();
            //SQLを作成
            String sql = "SELECT * FROM admin WHERE admin_mail = ? AND admin_password = ?";
            stmt = con.prepareStatement(sql);
            stmt.setString(1, adminMail);
            stmt.setString(2, password);

            //SQLの発行
            rs = stmt.executeQuery();
            rs.next();

            adminBeans = new AdminBeans();
            adminBeans.setAdminMail(rs.getString("admin_mail"));
            adminBeans.setAdminName(rs.getString("admin_name"));
            adminBeans.setAdminPassword(rs.getString("admin_password"));
            adminBeans.setPostalCode(rs.getInt("postal_code"));
            adminBeans.setAddress(rs.getString("address"));

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                this.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return adminBeans;
    }
```

2020-07-03 04:40 UTC, Sarada1101 commented on src/shop/model/service/MemberInsertCompleteServlet.java
> +
画面遷移の処理を追加してください

2020-07-03 04:40 UTC, Sarada1101 commented on src/shop/model/service/MemberInsertInputServlet.java
> +
画面遷移の処理を追加してください

2020-07-03 04:40 UTC, Sarada1101 commented on src/shop/model/service/UserService.java
> +
追加した部分をすべて削除してください

2020-07-03 04:40 UTC, Sarada1101 commented on src/shop/model/servlet/MemberInsertCheckServlet.java
> +		String member_mail = request.getParameter("member_mail");
変数名をすべてキャメルケースにしてください
コーディング規約.pdfにちゃんと目を通してください

2020-07-03 04:40 UTC, Sarada1101 commented on src/shop/model/servlet/MemberInsertCompleteServlet.java
> +
ここでUserServiceのインスタンスを生成してください

2020-07-03 04:40 UTC, Sarada1101 commented on src/shop/model/servlet/MemberInsertCompleteServlet.java
> +		UserService userService = new UserService();
削除してください

2020-07-03 04:44 UTC, NekoSarada1101 requested changes

2020-07-03 04:44 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_complete.jsp
> +<title>Insert title here</title>
会員情報登録完了に変更してください

2020-07-03 04:44 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_input.jsp
> +<title>Insert title here</title>
会員情報登録入力に変更してください

2020-07-03 04:57 UTC, NekoSarada1101 requested changes

2020-07-03 04:57 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_check.jsp
> +<form action="" method="post">
actionに遷移先を指定してください

2020-07-03 04:57 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/member/member_insert_input.jsp
> +<form action="" method="post">
actionに遷移先を指定してください
get,postも忘れずに

2020-07-03 05:08 UTC, NekoSarada1101 requested changes

2020-07-03 05:08 UTC, Sarada1101 commented on src/shop/model/service/MemberInsertInputServlet.java
> +public class MemberInsertInputServlet extends HttpServlet {
アノテーション書いてください

2020-07-03 05:08 UTC, Sarada1101 commented on src/shop/model/service/MemberInsertCompleteServlet.java
> +public class MemberInsertCompleteServlet extends HttpServlet {
アノテーション書いてください

2020-07-03 05:08 UTC, Sarada1101 commented on src/shop/model/servlet/MemberInsertCompleteServlet.java
> +public class MemberInsertCompleteServlet extends HttpServlet {
アノテーション書いてください

2020-07-03 05:08 UTC, Sarada1101 commented on src/shop/model/servlet/MemberInsertInputServlet.java
> +@WebServlet("/MemberInsertInputServlet")
正しいアノテーション書いてください

2020-07-03 05:13 UTC, NekoSarada1101 requested changes

2020-07-03 05:13 UTC, Sarada1101 commented on src/shop/model/servlet/MemberInsertInputServlet.java
> +				RequestDispatcher dispatch = request.getRequestDispatcher("member_insert_input.jsp");
URLを WEB-INF/jsp/user/cart_display.jsp の形に変更

2020-07-10 03:16 UTC, Sarada1101 commented on WebContent/WEB-INF/jsp/user/member_insert_input.jsp
if文を消してください

2020-07-10 08:04 UTC, merged